In [1]:
import numpy as np

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [9]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [10]:
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [11]:
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
arr1=np.arange(10).reshape(2,-1)
arr2=np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([arr1,arr2], axis=1))
print(np.concatenate([arr1,arr2], axis=0))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [17]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [18]:
np.setdiff1d(a,b)

array([1, 3, 5, 6])